# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
    - 8.1

# Commands to be run before your environment runs.
before_script:
    - composer self-update
    - composer install --prefer-source --no-interaction

# Commands you want to run that will verify your build.
script: php bin/phpunit --configuration phpunit.xml.dist --coverage-text

# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
    fast_finish: true

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: never
